name: Validate PR to PROD
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'force-app/**'
    branches: [ main ]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  validate-pr-to-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      # Checkout the Source code from the latest commit
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      #- name: Upgrade NPM to latest
      #  run: npm install -g npm@latest
          
      - name: Install Salesforce CLI
        run: |
         npm install @salesforce/cli --global
         sfdx --version

      - name: Install the sfdx-git-delta plugin
        run: |
          echo 'y' | sf plugins install sfdx-git-delta
                    
      - name: Decrypt the server.key.enc file & store inside assets folder
        run: |
          openssl enc -nosalt -aes-256-cbc -d -in ${{ vars.ENCRYPTION_KEY_FILE }} -out ${{ vars.JWT_KEY_FILE }} -base64 -K ${{ secrets.DECRYPTION_KEY }} -iv ${{ secrets.DECRYPTION_IV }}
        # openssl enc -nosalt -aes-256-cbc -d -in ${{ vars.ENCRYPTION_KEY_FILE }} -out ${{ vars.JWT_KEY_FILE }} -base64 -K ${{ secrets.DECRYPTION_KEY }} -iv ${{ secrets.DECRYPTION_IV }}
          
      - name: Authenticate Salesforce ORG
        run: |
          sfdx force:auth:jwt:grant -i ${{ secrets.HUB_CONSUMER_KEY }} -f ${{ vars.JWT_KEY_FILE }} --username ${{ vars.HUB_USER_NAME }}  -a HubOrg
      
      - name: Generate the package.xml for delta files
        run: |
          mkdir changed-sources
            sf sgd source delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/
      
      - name: validate Delta components to Salesforce
        run: |
          sf project deploy start --source-dir "changed-sources/force-app" --dry-run --target-org HubOrg --test-level NoTestRun
       
      - name: Validate destructive changes (if any)
        run: |
          sf deploy metadata --metadata-dir "changed-sources/destructiveChanges" --dry-run --target-org HubOrg --test-level NoTestRun
